### ISSUE TITLE
Studiorack Integration

### ISSUE THREAD

**Issue by RustoMCSpit** [Wasted-Audio/wstd-3q#1]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

If you have any questions or issues, make an issue in the Github repo or join the DIscord https://discord.gg/9D94f98PxP

**Comment by dromer** [comment]
Their build system is fundamentally broken and I'm not interested in it.

Sorry.

**Comment by RustoMCSpit** [comment]
> Their build system is fundamentally broken and I'm not interested in it.
> 
> Sorry.

could you make an issue in the github repo of what improvements youd recommend (if not already an issue there). thanks!

**Comment by dromer** [comment]
Sorry, but I am currently not interested in the project and will not spend time to open tickets for it.
